name: komodo_persistence_layer
description: Persistence layer abstractions for Flutter/Dart.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive:
    git:
      url: https://github.com/KomodoPlatform/hive.git
      path: hive/
      ref: 470473ffc1ba39f6c90f31ababe0ee63b76b69fe #2.2.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
